// <auto-generated />
using System;
using Blog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blog.Infrastructure.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    partial class BlogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Blog.Domain.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "admin",
                            Content = "Welcome to our little corner of the internet! This blog is built as a full-stack sample: an ASP.NET Core Web API following Clean Architecture on the back end, and an Angular application dressed up with daisyUI's emerald theme on the front end.\n\nBehind the scenes, everything is orchestrated with .NET Aspire. The AppHost wires up the API, a SQLite database, and a sqlite-web instance so you can peek at the data any time you like.\n\nBrowse around, read some posts, and if you are the admin, log in and start writing!",
                            CreatedAtUtc = new DateTime(2026, 8, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            PublishedAtUtc = new DateTime(2026, 8, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Title = "Welcome to the Emerald Blog",
                            UpdatedAtUtc = new DateTime(2026, 8, 20, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Author = "admin",
                            Content = "Clean Architecture is all about keeping business logic at the center of your solution, with infrastructure and delivery mechanisms pushed to the edges.\n\nIn this solution, Blog.Domain holds the entities and nothing else. Blog.Application depends only on the domain and defines the use cases and abstractions. Blog.Infrastructure implements those abstractions with EF Core and SQLite. Finally, Blog.Api is a thin delivery layer with controllers and authentication.\n\nThe payoff? You can swap SQLite for PostgreSQL, or the HTTP API for gRPC, without touching the core of the application.",
                            CreatedAtUtc = new DateTime(2026, 8, 26, 14, 30, 0, 0, DateTimeKind.Utc),
                            PublishedAtUtc = new DateTime(2026, 8, 26, 14, 30, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Title = "Why Clean Architecture still matters",
                            UpdatedAtUtc = new DateTime(2026, 8, 26, 14, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Author = "admin",
                            Content = ".NET Aspire gives local distributed apps a home: one AppHost project that describes every resource, and a dashboard that shows them all with logs, traces, and health at a glance.\n\nHere, the AppHost registers the blog-api on HTTP port 10010 and HTTPS port 10011, a SQLite database resource, and a sqlite-web container on port 10001 for browsing the database in your browser.\n\nEndpoints, connection strings, and service discovery are wired automatically, which means less plumbing and more building.",
                            CreatedAtUtc = new DateTime(2026, 9, 2, 11, 15, 0, 0, DateTimeKind.Utc),
                            PublishedAtUtc = new DateTime(2026, 9, 2, 11, 15, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Title = "A quick tour of .NET Aspire orchestration",
                            UpdatedAtUtc = new DateTime(2026, 9, 2, 11, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Author = "admin",
                            Content = "A rough draft that is only visible to the admin. Publish it from the editor when it is ready!\n\nRemember: a good post has one clear idea, a friendly voice, and a call to action.",
                            CreatedAtUtc = new DateTime(2026, 9, 12, 16, 45, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Title = "Draft: thoughts on writing your first blog post",
                            UpdatedAtUtc = new DateTime(2026, 9, 12, 16, 45, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
