<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>10a29fba-7c45-4627-8aa4-d25971e27b54</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.Sqlite" Version="13.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlogApi.Api\BlogApi.Api.csproj" />
  </ItemGroup>

</Project>
